### ISSUE TITLE
Missing validity-check when entering date for "Downtime"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1154]
It is possible to enter dates for Downtime that are "beyond" 2038-01-19, which translates to a negative timestamp.
These dates can not be handled very well by Nagios.

![2022-01-18_16-26](https://user-images.githubusercontent.com/26163222/149967497-ed4bc11f-d339-4d94-b3ac-fcb1a4f6af27.png)

It would be cool to prohibit such dates.

Thruk Version: 2.46-2 (from ConsolLabs)
Nagios: 4.4.6

-- 
Dan

**Comment by dan-m-joh** [comment]
This is on Nagios running on a RedHat Server.
```
$ uname -a
Linux nagios 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 9 16:09:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

**Comment by sni** [comment]
Just tested this. I can confirm the issue. But i'd say this should be fixed in the nagios core instead. As a workaroud you could set the `downtime_max_duration` to a couple of years:
http://thruk.org/documentation/configuration.html#_downtime_max_duration

**Comment by dan-m-joh** [comment]
Thanks for the Feedback.

Good idea!

Regards,
Dan

**Comment by sni** [comment]
Btw, i just checked the naemon source which should be still quite similar to nagios in those areas and it uses the time_t type which is 64bit after linux 5.6 from 2020. So the issue should
be fine once you update on rhel/rocky 8 or 9.
Also i noticed an issue in the livestatus module, but this should be fixed separately.

**Comment by pvdputte** [comment]
Is it possible that these issues in livestatus (or LMD?) still exist? I came across this while checking why I got negative timestamps when synchronizing downtimes to a 'testing' instance of our monitoring system.

Then I tested adding a downtime in some future where I hope I'm retired already, but still:

![Image](https://github.com/user-attachments/assets/509b402e-0b66-4867-9301-e48a4d667e47)

Using Debian 12, naemon & livestatus 1.4.2, lmd 2.4.0 (go1.24.1), Thruk 3.20.

I'll use the `downtime_max_duration` workaround, great suggestion.

**Comment by sni** [comment]
I recently fixed it (again) but it has not yet made it into a release. The timestamps are fine in
naemon-core but livestatus made them int32 again. This has been fixed and merged earlier this
year and now waits for the next naemon release.

- https://github.com/naemon/naemon-livestatus/pull/132
