### ISSUE TITLE
Missing pager on Configuration page

### ISSUE THREAD

**Issue by Hyllegaard** [sni/Thruk#443]
Hi.

I am using the latest Naemon with Thruk 1.86 from the Naemon repository.
When i choose Configuration in the menu, and then select Services, I am only shown the first 100 entries. There is no pager, and no option to change the number of entries shown. I don't know if this applies to the other object types, as services is the only that i have more than 100 of. But if I manually append &entries=500 to the URL I am shown more.

Regards

Jens

**Comment by sni** [comment]
I cannot reproduce that. Is this still the case? I have 2 pager on the configuration page, one above and one below the data table.

**Comment by Hyllegaard** [comment]
Hi.

Yeah, sorry that I did not check up on this.
I have just tested it on version 1.89-20150509 and the pager is indeed where it is supposed to be.

Thanks
Regards

Jens

**Comment by Hyllegaard** [comment]
Sorry again. But the error is still present in 1.89-20150509. I am not able to test the latest version right now, but as soon as I can, I will. Here are screen grabs that show the problem.
When either paging_steps is set to 500 in the config file or the &entries=500 is set everything works fine.
![thruk-500](https://cloud.githubusercontent.com/assets/2233675/7847348/2d12b3ea-04c3-11e5-8c86-93f4f5adefb5.png)
But if i set paging_steps to 100 only 100 are shown:
![thruk-500](https://cloud.githubusercontent.com/assets/2233675/7847362/47c28256-04c3-11e5-9903-1eeb6157ef5d.png)

This only occurs when looking at Configuration of services.

As I stated earlier, I will check out the latest version as soon as possible.

Regards

Jens

**Comment by sni** [comment]
Nothing's changed there lately, so i doubt this will help. Still unable to reproduce thought. I will check with a Naemon core tomorrow.

**Comment by Hyllegaard** [comment]
I just tried manually limiting the number of entries shown through the &entries= part of the URL.
If I set it to something small like 10, it works just fine for all but hosts and services under configuration. All the other configuration types are showing the pager perfectly fine, but hosts and services just show the number of items set in the URL and no more...

This is not a problem when showing the status pages for hosts or services. Only the configuration pages.

I will patiently wait for your tests :)

Regards

Jens

**Comment by sni** [comment]
cannot reproduce it with Naemon and current Thruk Master, so i'd assume this is fixed with the next release. Could you try the latest snapshot?

**Comment by Hyllegaard** [comment]
Is that the one that is called: 1.0.4-20150523 ?

**Comment by sni** [comment]
yes, that should contain the rewritten pager already.

**Comment by Hyllegaard** [comment]
Hi.
It is still not working in 1.0.4-20150523.
I have two separate installs where this problem exists. Both have been installed via the consol.de repository.
