### ISSUE TITLE
Thruk reporting and LMD

### ISSUE THREAD

**Issue by queox** [sni/Thruk#699]
Hi Sven,

first I'd like to thank you for fixing the issue #676.

Now I'm having another issue with the reports2 plugin with Thruk 2.14, when I activate the Livestatus Multi Deamon, reports can not be generated anymore.
---my config---
Host: Linux 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 GNU/Linux
release: CentOS release 6.8 (Final)
LMD: cat /etc/thruk/thruk_local.d/lmd.conf
use_lmd_core=1
lmd_core_bin=/opt/local/go/bin/lmd

Error Message: 
failed - The request contains an invalid header. at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378 on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.

When I disable the LMD config, reports work out fine again.

Thanks in advance for your help, best regards
Kurt

**Comment by sni** [comment]
Which LMD version is that? I've got the feeling that this is already fixed.

**Comment by queox** [comment]
wow, that was a fast response!

/opt/local/go/bin/lmd -version
lmd - version 1.0.2 (Build: )

rpm -qa |grep thruk
thruk-plugin-reporting-2.14-1.x86_64
thruk-base-2.14-1.x86_64
thruk-2.14-1.x86_64
libthruk-2.14-1.el6.x86_64

I'm using this repo:
https://labs.consol.de/repo/stable/rhel6/x86_64

**Comment by sni** [comment]
there is a lmd 1.0.3 already, please try that one.

**Comment by queox** [comment]
just did a upgrade to version 1.0.3
/opt/local/go/bin/lmd -version
lmd - version 1.0.3 (Build: )
but the error still persists, unfortunately:
The request contains an invalid header. at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378 on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.

**Comment by sni** [comment]
Cannot reproduce that, could you attach the report file? (Removing confidential data before)

**Comment by queox** [comment]
Sorry, i can not attach the pdf report file - the report can not be generated at all.
Or do you mean other log files? Thanks!

**Comment by sni** [comment]
i was talking about the report file from `/var/lib/thruk/reports`, but a screenshot from the report edit page would work as well. I just want to create a similar report here to reproduce the error.

**Comment by queox** [comment]
sorry for the late reply, please find the screenshot below:
![auswahl_003](https://cloud.githubusercontent.com/assets/25194875/24599551/022a48de-1851-11e7-8a01-b23439d8c1fc.png)

**Comment by sni** [comment]
Still cannot reproduce it, it just works. Is there anything in the LMD logfile?

**Comment by queox** [comment]
I'm getting this warnings in /var/cache/thruk/lmd/lmd.log
[2017-04-04 08:53:01][Warn][response.go:361] client error: read tcp <scrubbed>: i/o timeout

**Comment by sni** [comment]
Depending on the amount of services, it might help to use the logcache. Or increase the network timeout in LMD.

**Comment by queox** [comment]
I'd like to give the higher network timeout setting a try, took a look at: https://www.thruk.org/documentation/configuration.html but couldn't find where to setup this timeout settings in lmd. Could you please give me a hint? thanks again!

**Comment by sni** [comment]
Its not a Thruk config option, see `NetTimeout` in https://github.com/sni/lmd/blob/master/lmd.ini.example

**Comment by queox** [comment]
OK, I ended up with the logcache & MySQL option because the NetTimeout setting in lmd.ini didn't work out. Thanks for your help!
